ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]

uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]

resume_videos = [ 'https://youtu.be/Tt08KmFfIYQ','https://youtu.be/y8YH0Qbu5h4',
                  'https://youtu.be/u75hUSShvnc','https://youtu.be/BYUy1yvjHxE',
                  'https://youtu.be/KFaugkGVeNQ','https://youtu.be/3agP4x8LYFM',
                  'https://youtu.be/GyjzOKdaioU','https://youtu.be/17YZBH_qtmg',
                  'https://youtu.be/C7pNLIq3kOI','https://youtu.be/xpaz7nrNmXA',
                  'https://youtu.be/aKjsy-b00QM','https://youtu.be/ciIkiWwZnlc']

interview_videos = ['https://youtu.be/HG68Ymazo18','https://youtu.be/BOvAAoxM4vg',
                    'https://youtu.be/KukmClH1KoA','https://youtu.be/7_aAicmPB3A',
                    'https://youtu.be/1mHjMNZZvFo','https://youtu.be/WfdtKbAJOmE',
                    'https://youtu.be/IBjM-F56qS0','https://youtu.be/IBjM-F56qS0',
                    'https://youtu.be/4tYoVx0QoN0','https://youtu.be/Ge0Udbws1kc',
                    'https://youtu.be/thkuu_FWFD8','https://youtu.be/e0E6-dRPcJA',
                    'https://youtu.be/htT1bhFSNxo','https://youtu.be/TZ3C_syg9Ow']

genai_course = [["Generative AI with Large Language Models","https://www.coursera.org/learn/generative-ai-with-llms"],
                ["DeepLearning.AI Prompt Engineering [Free]","https://www.deeplearning.ai/short-courses/prompt-engineering/"],
                ["LangChain for LLM Application Development","https://learn.deeplearning.ai/courses/langchain/"],
                ["Vector Databases: Pinecone Basics [Free]","https://docs.pinecone.io/docs/overview"],
                ["Practical LLM Ops with Weights & Biases","https://www.wandb.courses/"],
                ["LlamaIndex 101 [Free]","https://docs.llamaindex.ai/"],
                ["OpenAI API for Developers","https://platform.openai.com/docs/overview"],
                ["Hands-on RAG Systems","https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/"],
                ["NVIDIA GenAI Fundamentals","https://learn.nvidia.com/"],
                ["Hugging Face Course [Free]","https://huggingface.co/learn"]]

cloud_course = [["AWS Certified Cloud Practitioner","https://www.aws.training/Details/Curriculum?id=20685"],
                ["Microsoft Azure Fundamentals (AZ-900)","https://learn.microsoft.com/en-us/certifications/azure-fundamentals/"],
                ["Google Cloud Digital Leader","https://www.cloudskillsboost.google/paths/11"],
                ["AWS Solutions Architect Associate","https://aws.amazon.com/certification/certified-solutions-architect-associate/"],
                ["Architecting with Google Compute Engine","https://www.coursera.org/specializations/gcp-architecture"],
                ["Azure Data Engineer (DP-203)","https://learn.microsoft.com/en-us/certifications/azure-data-engineer/"],
                ["Cloud FinOps Essentials [Free]","https://www.finops.org/"],
                ["Kubernetes on GKE","https://www.cloudskillsboost.google/quests/23"],
                ["AWS Well-Architected [Free]","https://aws.amazon.com/architecture/well-architected/"],
                ["Cloud Networking Basics","https://www.coursera.org/specializations/cloud-networking"]]

devops_course = [["Docker for the Absolute Beginner","https://kodekloud.com/courses/docker-for-the-absolute-beginner-hands-on/"],
                 ["Kubernetes Hands-on","https://www.udemy.com/course/learn-kubernetes/"],
                 ["CI/CD with GitHub Actions [Free]","https://docs.github.com/en/actions"],
                 ["Terraform on Azure/AWS","https://learn.hashicorp.com/terraform"],
                 ["Ansible for DevOps","https://www.ansible.com/resources/get-started"],
                 ["Cloud Native Fundamentals","https://www.edx.org/course/cloud-native-computing-foundation-xfalx103x"],
                 ["Helm and GitOps (ArgoCD)","https://argo-cd.readthedocs.io/en/stable/"],
                 ["Site Reliability Engineering","https://sre.google/books/"],
                 ["Monitoring with Prometheus & Grafana","https://grafana.com/tutorials/"],
                 ["AWS DevOps Engineer","https://aws.amazon.com/certification/certified-devops-engineer-professional/"]]

cyber_course = [["Introduction to Cyber Security [Free]","https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/entry/cyberops-associate.html"],
                ["CompTIA Security+","https://www.comptia.org/certifications/security"],
                ["Ethical Hacking (CEH)","https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/"],
                ["Blue Team Fundamentals","https://www.blue-team.com/"],
                ["OWASP Top 10 [Free]","https://owasp.org/www-project-top-ten/"],
                ["Network Security Essentials","https://www.coursera.org/specializations/network-security"],
                ["Incident Response & Forensics","https://www.sans.org/cyber-security-courses/"],
                ["Cloud Security (CCSP)","https://www.isc2.org/certifications/ccsp"],
                ["SIEM with Splunk","https://education.splunk.com/"],
                ["Bug Bounty Basics","https://www.hackerone.com/for-hackers"]]

data_eng_course = [["Data Engineering on Google Cloud","https://www.coursera.org/specializations/gcp-data-engineering"],
                    ["Databricks Lakehouse Fundamentals [Free]","https://academy.databricks.com/collections"],
                    ["Apache Spark Developer","https://spark.apache.org/"],
                    ["Apache Kafka Series","https://www.udemy.com/course/apache-kafka/"],
                    ["Airflow Fundamentals","https://www.astronomer.io/learn/"],
                    ["Snowflake Hands-on","https://learn.snowflake.com/"],
                    ["ETL Pipelines with Python","https://www.datacamp.com/courses/etl-pipelines-in-python"],
                    ["BigQuery for Data Engineers","https://www.cloudskillsboost.google/quests/11"],
                    ["dbt Fundamentals [Free]","https://courses.getdbt.com/"],
                    ["Delta Lake & Lakehouse","https://delta.io/"]]

qa_course = [["Selenium WebDriver with Python","https://www.udemy.com/course/selenium-webdriver-with-python3/"],
             ["Cypress End-to-End Testing","https://www.cypress.io/"],
             ["Playwright Testing","https://playwright.dev/docs/intro"],
             ["API Testing with Postman [Free]","https://learning.postman.com/"],
             ["JUnit/TestNG Basics","https://junit.org/junit5/"],
             ["Load Testing with JMeter","https://jmeter.apache.org/"],
             ["Mobile App Testing (Appium)","https://appium.io/"],
             ["Automation Framework Design","https://testautomationu.applitools.com/"],
             ["Performance & APM (New Relic)","https://learn.newrelic.com/"],
             ["QA Strategy and Test Design","https://www.ministryoftesting.com/"]]

product_course = [["Product Management by Reforge","https://www.reforge.com/"],
                  ["Product Strategy (North Star)","https://www.sachinrekhi.com/courses"],
                  ["Udacity Product Manager","https://www.udacity.com/course/product-manager-nanodegree--nd036"],
                  ["A/B Testing by Google","https://www.udacity.com/course/ab-testing--ud257"],
                  ["Metrics & Growth (Amplitude)","https://help.amplitude.com/hc/en-us/categories/360001807131-Amplitude-Academy"],
                  ["Roadmapping & Prioritization","https://www.productschool.com/"],
                  ["UX for PMs","https://www.interaction-design.org/"],
                  ["Storytelling and Communication","https://www.duarte.com/academy/"],
                  ["Pricing & Monetization","https://www.coursera.org/learn/monetization"],
                  ["Analytics for PM","https://mode.com/sql-tutorial"]]

blockchain_course = [["Blockchain Basics [Free]","https://www.coursera.org/learn/blockchain-basics"],
                     ["Ethereum and Solidity","https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/"],
                     ["Smart Contracts Security","https://www.damnvulnerabledefi.xyz/"],
                     ["Web3.js & Ethers.js","https://docs.ethers.org/"],
                     ["DeFi Concepts","https://www.coursera.org/specializations/defi"],
                     ["Solana Development","https://university.alchemy.com/"],
                     ["Hyperledger Fabric","https://www.hyperledger.org/learn"],
                     ["NFTs & Token Standards","https://docs.opensea.io/"],
                     ["Zero-Knowledge Proofs Intro","https://zkhack.dev/"],
                     ["Blockchain Architecture","https://www.edx.org/professional-certificate/iberostar-blockchain"]]

# --- Non-Tech & Cross-Functional Streams ---
marketing_course = [["Digital Marketing Specialization","https://www.coursera.org/specializations/digital-marketing"],
                    ["Google Ads Certification [Free]","https://skillshop.exceedlms.com/student/catalog"],
                    ["Meta Social Media Marketing","https://www.coursera.org/professional-certificates/meta-social-media-marketing"],
                    ["Content Marketing Certification [Free]","https://academy.hubspot.com/courses/content-marketing"],
                    ["Email Marketing Certification [Free]","https://academy.hubspot.com/courses/email-marketing"],
                    ["SEO Fundamentals","https://www.semrush.com/academy/"],
                    ["Google Analytics 4","https://skillshop.exceedlms.com/student/collection/ga4"],
                    ["Brand Management","https://www.coursera.org/learn/brand-management"],
                    ["Marketing Analytics","https://www.coursera.org/specializations/marketing-analytics"],
                    ["Product Marketing","https://www.productmarketingalliance.com/academy/"]]

sales_course = [["Sales Training: Practical Sales Techniques","https://www.udemy.com/course/sales-training-practical-sales-techniques/"],
                ["B2B Sales Skills","https://www.coursera.org/specializations/sales-skills"],
                ["Negotiation Skills","https://www.coursera.org/learn/negotiation-skills"],
                ["CRM with Salesforce","https://trailhead.salesforce.com/"],
                ["Cold Emailing & Prospecting","https://www.udemy.com/course/cold-emailing/"],
                ["Strategic Account Management","https://www.linkedin.com/learning/topics/account-management"],
                ["SPIN Selling Overview","https://www.linkedin.com/learning/search?keywords=spin%20selling"],
                ["Sales Analytics Basics","https://www.coursera.org/learn/sales-analytics"],
                ["Storytelling in Sales","https://www.duarte.com/academy/"],
                ["Objection Handling","https://www.linkedin.com/learning/topics/objection-handling"]]

finance_course = [["Corporate Finance Essentials","https://www.coursera.org/learn/corporate-finance-essentials"],
                  ["Financial Accounting","https://www.edx.org/course/financial-accounting"],
                  ["Investment Management","https://www.coursera.org/specializations/investment-management"],
                  ["Excel for Finance","https://www.coursera.org/learn/excel-for-business-essentials"],
                  ["FP&A Basics","https://cfouniversity.io/"],
                  ["Bloomberg Market Concepts","https://www.bloomberg.com/professional/product/bmc/"],
                  ["Valuation with DCF","https://www.wallstreetprep.com/"],
                  ["Financial Modeling","https://www.coursera.org/specializations/wharton-business-and-financial-modeling"],
                  ["Risk Management","https://www.coursera.org/specializations/financial-risk-management"],
                  ["FinTech Foundations","https://www.edx.org/learn/fintech"]]

hr_course = [["HR Management Specialization","https://www.coursera.org/specializations/human-resource-management"],
             ["Recruiting, Hiring, and Onboarding","https://www.coursera.org/specializations/recruiting"],
             ["Compensation and Benefits","https://www.linkedin.com/learning/topics/compensation-and-benefits"],
             ["HR Analytics","https://www.coursera.org/specializations/people-analytics"],
             ["Employee Relations","https://www.udemy.com/course/employee-relations/"],
             ["Labor Law Basics","https://www.coursera.org/learn/hiring-and-onboarding-employees"],
             ["Diversity, Equity & Inclusion","https://www.coursera.org/specializations/diversity-equity-inclusion"],
             ["Performance Management","https://www.coursera.org/learn/performance-management"],
             ["Learning & Development","https://www.linkedin.com/learning/topics/learning-and-development"],
             ["HRBP Skills","https://www.cipd.org/uk/learning/"],]

operations_course = [["Operations Management","https://www.coursera.org/learn/wharton-operations"],
                     ["Lean Six Sigma Yellow Belt [Free]","https://www.sixsigmadsi.com/lean-six-sigma-yellow-belt-training/"],
                     ["Process Improvement","https://www.coursera.org/specializations/business-process-management"],
                     ["Capacity Planning","https://www.linkedin.com/learning/topics/capacity-planning"],
                     ["Inventory & Supply Planning","https://www.coursera.org/learn/inventory-operations"],
                     ["Quality Management","https://asq.org/training"],
                     ["Procurement & Sourcing","https://www.coursera.org/specializations/strategic-sourcing"],
                     ["Warehouse & Logistics","https://www.edx.org/learn/logistics"],
                     ["Process Mapping","https://www.udemy.com/course/business-process-mapping/"],
                     ["Service Operations","https://www.coursera.org/learn/service-operations"]]

supply_chain_course = [["Supply Chain Management","https://www.coursera.org/specializations/supply-chain-management"],
                       ["Demand Forecasting","https://www.linkedin.com/learning/topics/demand-forecasting"],
                       ["Logistics & Transportation","https://www.edx.org/learn/logistics"],
                       ["SCM Analytics","https://www.coursera.org/learn/supply-chain-analytics"],
                       ["S&OP Fundamentals","https://apics.org/"],
                       ["Procurement Fundamentals","https://www.udemy.com/course/procurement-management/"],
                       ["Cold Chain Logistics","https://www.edx.org/"],
                       ["International Trade","https://www.coursera.org/specializations/international-business-essentials"],
                       ["Excel for SCM","https://www.udemy.com/course/excel-for-supply-chain-analytics/"],
                       ["Warehouse Ops","https://www.udemy.com/course/warehouse-management/"]]

project_mgmt_course = [["Google Project Management Professional Certificate","https://www.coursera.org/professional-certificates/google-project-management"],
                       ["PMP Exam Prep","https://www.udemy.com/course/pmp-pmbok6-35-pdus-project-management-professional-certification-exam-prep/"],
                       ["Agile with Jira","https://www.atlassian.com/university"],
                       ["Scrum Master (PSM I)","https://www.scrum.org/professional-scrum-certification-psm-i"],
                       ["Stakeholder Management","https://www.coursera.org/learn/uva-darden-project-management"],
                       ["Risk & Issue Management","https://www.linkedin.com/learning/topics/project-risk-management"],
                       ["Project Finance Basics","https://www.coursera.org/specializations/project-finance"],
                       ["Requirements & Scope","https://www.coursera.org/learn/project-planning"],
                       ["MS Project/Smartsheet","https://www.smartsheet.com/learning-center"],
                       ["Change Management","https://www.prosci.com/training"]]

business_analysis_course = [["Business Analysis Fundamentals","https://www.udemy.com/course/business-analysis-fundamentals/"],
                            ["SQL for Business Analysts","https://mode.com/sql-tutorial"],
                            ["Requirements Gathering","https://www.coursera.org/learn/requirements-gathering"],
                            ["User Stories & Acceptance Criteria","https://www.udemy.com/course/product-owner/"],
                            ["Process Modeling (BPMN)","https://www.udemy.com/course/business-process-modeling/"],
                            ["Wireframing & Prototyping","https://www.interaction-design.org/"],
                            ["Stakeholder Mapping","https://www.coursera.org/learn/uva-darden-stakeholder-management"],
                            ["A/B Testing for Biz","https://www.udacity.com/course/ab-testing--ud257"],
                            ["Analytics for Biz","https://www.coursera.org/learn/wharton-people-analytics"],
                            ["Storytelling with Data","https://www.storytellingwithdata.com/lessons"]]

entrepreneurship_course = [["Y Combinator Startup School [Free]","https://www.startupschool.org/"],
                           ["Lean Startup & Customer Discovery","https://www.coursera.org/learn/wharton-entrepreneurship"],
                           ["Building a Startup MVP","https://www.udacity.com/course/how-to-build-a-startup--ep245"],
                           ["Fundraising & Term Sheets","https://www.coursera.org/learn/venture-capital"],
                           ["Product-Market Fit","https://www.reforge.com/"],
                           ["Growth Hacking","https://www.coursera.org/learn/growth-marketing"],
                           ["Startup Finance","https://www.coursera.org/learn/startup-financing"],
                           ["Startup Legal Basics","https://www.udemy.com/course/startup-law/"],
                           ["No-Code Tools","https://www.makerpad.co/"],
                           ["Pitching & Storytelling","https://www.duarte.com/academy/"]]

admin_course = [["Office Administration","https://www.coursera.org/specializations/office-administration"],
                ["MS Office Specialization","https://learn.microsoft.com/en-us/training/"],
                ["Scheduling & Calendar Management","https://www.linkedin.com/learning/topics/calendar-management"],
                ["Travel & Expense","https://www.udemy.com/course/travel-management/"],
                ["Business Communication","https://www.coursera.org/specializations/business-communication"],
                ["Minutes & Documentation","https://www.udemy.com/course/minute-taking-at-meetings/"],
                ["Vendor Management","https://www.coursera.org/learn/vendor-management"],
                ["Basic Bookkeeping","https://www.coursera.org/specializations/small-business-bookkeeping"],
                ["Procurement Basics","https://www.udemy.com/course/procurement-management/"],
                ["Office Management","https://www.linkedin.com/learning/topics/office-management"]]

education_course = [["Teaching Strategies","https://www.coursera.org/specializations/teaching-strategies"],
                    ["Instructional Design","https://www.coursera.org/specializations/instructional-design"],
                    ["Educational Technology","https://www.edx.org/learn/education-technology"],
                    ["Assessment & Evaluation","https://www.coursera.org/learn/educational-assessment"],
                    ["Classroom Management","https://www.udemy.com/course/classroom-management/"],
                    ["Curriculum Design","https://www.coursera.org/learn/curriculum-design"],
                    ["Early Childhood Education","https://www.coursera.org/specializations/early-childhood-education"],
                    ["Special Education","https://www.coursera.org/specializations/special-education"],
                    ["Learning Analytics","https://www.coursera.org/specializations/learning-analytics"],
                    ["Teacher Leadership","https://www.coursera.org/specializations/teacher-leadership"]]

psychology_course = [["Introduction to Psychology [Free]","https://www.edx.org/course/introduction-to-psychology"],
                     ["Counseling Skills","https://www.coursera.org/specializations/counseling"],
                     ["Organizational Psychology","https://www.coursera.org/learn/organizational-analysis"],
                     ["Clinical Psychology Basics","https://www.udemy.com/course/clinical-psychology/"],
                     ["Research Methods","https://www.coursera.org/learn/research-methods"],
                     ["Cognitive Behavioral Therapy","https://www.coursera.org/specializations/cbt-therapy"],
                     ["Positive Psychology","https://www.coursera.org/learn/positive-psychology"],
                     ["Child Psychology","https://www.udemy.com/course/child-psychology/"],
                     ["Neuropsychology Basics","https://www.edx.org/learn/neuroscience"],
                     ["Data for Psych","https://www.datacamp.com/"],]

law_course = [["Introduction to American Law","https://www.coursera.org/learn/american-law"],
              ["Contract Law","https://www.edx.org/course/contract-law-from-trust-to-promise-to-contract"],
              ["Corporate Law","https://www.coursera.org/learn/corporate-commercial-law"],
              ["IP Law Basics","https://www.coursera.org/learn/intellectual-property-law"],
              ["International Law","https://www.coursera.org/specializations/international-law"],
              ["Legal Writing","https://www.coursera.org/learn/legal-writing"],
              ["Privacy & Compliance","https://www.coursera.org/specializations/data-privacy"],
              ["Cyber Law","https://www.udemy.com/course/cyberlaw/"],
              ["Mooting & Research","https://www.linkedin.com/learning/topics/legal-research"],
              ["Legal Tech Overview","https://www.coursera.org/learn/legaltech"]]

healthcare_course = [["Healthcare Administration","https://www.coursera.org/specializations/healthcare-administration"],
                     ["Public Health","https://www.coursera.org/specializations/public-health"],
                     ["Medical Terminology","https://www.edx.org/learn/medical-terminology"],
                     ["Health Informatics","https://www.coursera.org/specializations/health-informatics"],
                     ["Clinical Trials","https://www.coursera.org/specializations/clinical-trials"],
                     ["Healthcare Quality & Safety","https://www.coursera.org/specializations/quality-improvement-healthcare"],
                     ["Telehealth Basics","https://www.udemy.com/course/telemedicine/"],
                     ["Healthcare Finance","https://www.coursera.org/learn/healthcare-finance"],
                     ["Health Policy","https://www.coursera.org/specializations/health-policy"],
                     ["Medical Ethics","https://www.coursera.org/learn/bioethics"]]

nursing_course = [["Foundations of Nursing","https://www.edx.org/learn/nursing"],
                  ["Patient Care & Safety","https://www.coursera.org/learn/patient-safety"],
                  ["Emergency & Critical Care","https://www.udemy.com/topic/critical-care-nursing/"],
                  ["Pharmacology for Nurses","https://www.coursera.org/specializations/pharmacology"],
                  ["Evidence-Based Practice","https://www.coursera.org/learn/ebp"],
                  ["Palliative Care","https://www.coursera.org/specializations/palliative-care"],
                  ["Mental Health Nursing","https://www.udemy.com/topic/psychiatric-nursing/"],
                  ["Pediatric Nursing","https://www.udemy.com/topic/pediatric-nursing/"],
                  ["ICU Essentials","https://www.udemy.com/topic/icu/"],
                  ["Nursing Leadership","https://www.linkedin.com/learning/topics/nursing-leadership"]]

medical_coding_course = [["Medical Coding Basics","https://www.udemy.com/course/medical-coding/"],
                         ["ICD-10 & CPT","https://www.aapc.com/training/"],
                         ["Revenue Cycle Management","https://www.coursera.org/learn/healthcare-it-support"],
                         ["HIPAA & Compliance","https://www.hhs.gov/hipaa/for-professionals/training/index.html"],
                         ["EHR Systems Intro","https://www.coursera.org/learn/ehr"],
                         ["Denials & Appeals","https://www.udemy.com/course/denial-management/"],
                         ["Medical Billing","https://www.udemy.com/course/medical-billing/"],
                         ["Audit Techniques","https://www.aapc.com/training/"],
                         ["Pathology Coding","https://www.udemy.com/topic/pathology/"],
                         ["Risk Adjustment","https://www.aapc.com/training/"]]

pharmacy_course = [["Pharmacy Technician Basics","https://www.coursera.org/learn/pharmacy-technician"],
                   ["Clinical Pharmacology","https://www.coursera.org/specializations/pharmacology"],
                   ["Drug Safety & PV","https://www.coursera.org/learn/pharmacovigilance"],
                   ["Compounding & Dispensing","https://www.udemy.com/topic/pharmacy/"],
                   ["Medication Therapy Management","https://www.coursera.org/learn/medication-management"],
                   ["Regulatory Affairs","https://www.coursera.org/specializations/regulatory-affairs"],
                   ["Pharmaceutics","https://www.edx.org/learn/pharmaceutics"],
                   ["Pharmacokinetics","https://www.edx.org/learn/pharmacokinetics"],
                   ["Drug Interactions","https://www.udemy.com/topic/drug-interactions/"],
                   ["Clinical Trials for Pharmacists","https://www.coursera.org/learn/clinical-trials"]]

graphic_design_course = [["Graphic Design Specialization","https://www.coursera.org/specializations/graphic-design"],
                         ["Adobe Photoshop [Free]","https://helpx.adobe.com/support/photoshop.html"],
                         ["Adobe Illustrator [Free]","https://helpx.adobe.com/support/illustrator.html"],
                         ["Canva Design School [Free]","https://www.canva.com/designschool/"],
                         ["Typography Basics","https://www.coursera.org/learn/typography"],
                         ["Brand Identity Design","https://www.udemy.com/course/brand-identity-design/"],
                         ["Color Theory","https://www.udemy.com/course/color-theory/"],
                         ["Layout & Composition","https://www.linkedin.com/learning/topics/layout-and-composition"],
                         ["Packaging Design","https://www.udemy.com/topic/package-design/"],
                         ["Motion Graphics","https://www.coursera.org/specializations/motion-graphics"]]

journalism_course = [["Journalism Essentials","https://www.coursera.org/learn/journalism"],
                     ["Investigative Journalism","https://www.udemy.com/course/investigative-journalism/"],
                     ["Data Journalism","https://www.coursera.org/learn/data-driven-journalism"],
                     ["Multimedia Reporting","https://www.coursera.org/learn/multimedia-journalism"],
                     ["Editorial Standards","https://www.bbc.co.uk/editorialguidelines"],
                     ["Copy Editing","https://www.coursera.org/learn/copy-editing"],
                     ["Fact Checking","https://www.poynter.org/learn/"],
                     ["Media Law","https://www.coursera.org/learn/media-ethics-law"],
                     ["Podcast Journalism","https://www.udemy.com/course/podcast-journalism/"],
                     ["Mobile Journalism","https://www.coursera.org/learn/mobile-journalism"]]

content_writing_course = [["Content Writing Basics","https://www.udemy.com/course/complete-content-writing-course/"],
                          ["Technical Writing","https://developers.google.com/tech-writing"],
                          ["Copywriting","https://www.coursera.org/specializations/copywriting"],
                          ["SEO Writing","https://www.semrush.com/academy/"],
                          ["Blogging & Editorial","https://www.udemy.com/course/blogging/"],
                          ["Scriptwriting","https://www.coursera.org/specializations/scriptwriting"],
                          ["UX Writing","https://www.coursera.org/learn/ux-writing"],
                          ["Grant Writing","https://www.coursera.org/specializations/grant-proposal"],
                          ["Storytelling","https://www.duarte.com/academy/"],
                          ["Newsletter Writing","https://www.linkedin.com/learning/topics/newsletters"]]

soft_skills_course = [["Communication Skills","https://www.coursera.org/specializations/wharton-communication-skills"],
                      ["Public Speaking","https://www.coursera.org/specializations/public-speaking"],
                      ["Time Management","https://www.coursera.org/learn/work-smarter-not-harder"],
                      ["Emotional Intelligence","https://www.coursera.org/learn/emotional-intelligence-at-work"],
                      ["Leadership Fundamentals","https://www.coursera.org/specializations/leading-teams"],
                      ["Critical Thinking","https://www.edx.org/learn/critical-thinking"],
                      ["Teamwork & Collaboration","https://www.coursera.org/learn/leading-teams"],
                      ["Negotiation","https://www.coursera.org/learn/negotiation-skills"],
                      ["Conflict Resolution","https://www.linkedin.com/learning/topics/conflict-resolution"],
                      ["Career Planning","https://www.coursera.org/learn/career-planning"]]

# Extend the global mapping
career_streams = {
    'Data Science / ML': ds_course,
    'Web Development': web_course,
    'Android Development': android_course,
    'iOS Development': ios_course,
    'UI/UX Design': uiux_course,
    'Generative AI / LLMs': genai_course,
    'Cloud': cloud_course,
    'DevOps & SRE': devops_course,
    'Cybersecurity': cyber_course,
    'Data Engineering': data_eng_course,
    'QA / Test Automation': qa_course,
    'Product Management': product_course,
    'Blockchain / Web3': blockchain_course,
    'Marketing': marketing_course,
    'Sales': sales_course,
    'Finance': finance_course,
    'Human Resources (HR)': hr_course,
    'Operations': operations_course,
    'Supply Chain': supply_chain_course,
    'Project Management': project_mgmt_course,
    'Business Analysis': business_analysis_course,
    'Entrepreneurship': entrepreneurship_course,
    'Administration': admin_course,
    'Education': education_course,
    'Psychology': psychology_course,
    'Law': law_course,
    'Healthcare': healthcare_course,
    'Nursing': nursing_course,
    'Medical Coding': medical_coding_course,
    'Pharmacy': pharmacy_course,
    'Graphic Design': graphic_design_course,
    'Journalism': journalism_course,
    'Content Writing': content_writing_course,
    'Soft Skills': soft_skills_course,
}